name: flutter_advanced
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  go_router: ^14.6.1
  http: ^1.2.2
  phoenix_socket: ^0.7.6
  rfw: ^1.0.30

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
